// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gemini.proto

package gemini // import "github.com/Finciero/opendata/gemini/gemini"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import saga "github.com/Finciero/opendata/gemini/saga"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Card struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_gemini_7e4f8e3cc7c65d69, []int{0}
}
func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (dst *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(dst, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Card) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RefereceId           string   `protobuf:"bytes,3,opt,name=referece_id,json=refereceId,proto3" json:"referece_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_gemini_7e4f8e3cc7c65d69, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Request) GetRefereceId() string {
	if m != nil {
		return m.RefereceId
	}
	return ""
}

type Response struct {
	StatusCode           int32         `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Balance              *saga.Balance `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_gemini_7e4f8e3cc7c65d69, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetBalance() *saga.Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type Account struct {
	ReferenceId          string   `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceUserId      string   `protobuf:"bytes,2,opt,name=reference_user_id,json=referenceUserId,proto3" json:"reference_user_id,omitempty"`
	ReferenceEmail       string   `protobuf:"bytes,3,opt,name=reference_email,json=referenceEmail,proto3" json:"reference_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_gemini_7e4f8e3cc7c65d69, []int{3}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetReferenceId() string {
	if m != nil {
		return m.ReferenceId
	}
	return ""
}

func (m *Account) GetReferenceUserId() string {
	if m != nil {
		return m.ReferenceUserId
	}
	return ""
}

func (m *Account) GetReferenceEmail() string {
	if m != nil {
		return m.ReferenceEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*Card)(nil), "gemini.Card")
	proto.RegisterType((*Request)(nil), "gemini.Request")
	proto.RegisterType((*Response)(nil), "gemini.Response")
	proto.RegisterType((*Account)(nil), "gemini.Account")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Card(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Card(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/gemini.Service/Card", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Card(context.Context, *Request) (*Response, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Card_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Card(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gemini.Service/Card",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Card(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gemini.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Card",
			Handler:    _Service_Card_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gemini.proto",
}

func init() { proto.RegisterFile("gemini.proto", fileDescriptor_gemini_7e4f8e3cc7c65d69) }

var fileDescriptor_gemini_7e4f8e3cc7c65d69 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4f, 0x32, 0x31,
	0x10, 0xc5, 0xc3, 0xf7, 0x09, 0x0b, 0x03, 0x8a, 0x36, 0x26, 0x12, 0x3c, 0xa8, 0x7b, 0x41, 0x89,
	0x59, 0x12, 0xf4, 0xe0, 0x55, 0x88, 0x26, 0x7b, 0x5d, 0xf5, 0xe2, 0x05, 0x4b, 0x3b, 0x62, 0x13,
	0x68, 0xd7, 0xb6, 0xab, 0x67, 0xff, 0x73, 0xb3, 0x9d, 0x65, 0x89, 0xa7, 0xe6, 0xfd, 0xde, 0xa4,
	0x33, 0x6f, 0x06, 0x7a, 0x2b, 0xdc, 0x28, 0xad, 0x92, 0xdc, 0x1a, 0x6f, 0x58, 0x8b, 0xd4, 0x10,
	0x1c, 0x5f, 0x71, 0x62, 0xf1, 0x1d, 0xec, 0xcd, 0xb9, 0x95, 0xec, 0x18, 0x9a, 0xb8, 0xe1, 0x6a,
	0x3d, 0x68, 0x9c, 0x37, 0x2e, 0x3b, 0x19, 0x09, 0x36, 0x84, 0x76, 0xce, 0x9d, 0xfb, 0x36, 0x56,
	0x0e, 0xfe, 0x05, 0xa3, 0xd6, 0xf1, 0x1b, 0x44, 0x19, 0x7e, 0x16, 0xe8, 0x3c, 0x3b, 0x85, 0x8e,
	0x58, 0x2b, 0xd4, 0x7e, 0xa1, 0x64, 0xf5, 0x41, 0x9b, 0x40, 0x2a, 0xd9, 0x09, 0x44, 0x85, 0x43,
	0x5b, 0x5a, 0xf4, 0x45, 0xab, 0x94, 0xa9, 0x64, 0x67, 0xd0, 0xb5, 0xf8, 0x8e, 0x16, 0x05, 0x96,
	0xe6, 0xff, 0x60, 0xc2, 0x16, 0xa5, 0x32, 0x7e, 0x86, 0x76, 0x86, 0x2e, 0x37, 0xda, 0x61, 0x59,
	0xec, 0x3c, 0xf7, 0x85, 0x5b, 0x08, 0x23, 0x31, 0x34, 0x69, 0x66, 0x40, 0x68, 0x6e, 0x24, 0xb2,
	0x11, 0x44, 0x4b, 0xbe, 0xe6, 0x5a, 0x60, 0x68, 0xd3, 0x9d, 0xee, 0x27, 0x21, 0xe6, 0x8c, 0x60,
	0xb6, 0x75, 0xe3, 0x9f, 0x06, 0x44, 0xf7, 0x42, 0x98, 0x42, 0x7b, 0x76, 0x01, 0x3d, 0xea, 0xa7,
	0x69, 0x06, 0x9a, 0xbd, 0x5b, 0xb3, 0x54, 0xb2, 0x31, 0x1c, 0xed, 0x4a, 0xfe, 0x06, 0xe9, 0xd7,
	0xc6, 0x0b, 0x25, 0x1a, 0xc1, 0x0e, 0x2d, 0x68, 0x9d, 0x94, 0xea, 0xa0, 0xc6, 0x0f, 0x25, 0x9d,
	0xde, 0x42, 0xf4, 0x84, 0xf6, 0x4b, 0x09, 0x64, 0x57, 0xd5, 0x01, 0xfa, 0x49, 0x75, 0xab, 0x6a,
	0xa9, 0xc3, 0xc3, 0x1d, 0xa0, 0x1d, 0xcc, 0xae, 0x5f, 0xc7, 0x2b, 0xe5, 0x3f, 0x8a, 0x65, 0x22,
	0xcc, 0x66, 0xf2, 0xa8, 0xb4, 0x50, 0x68, 0xcd, 0xc4, 0xe4, 0xa8, 0x25, 0xf7, 0x7c, 0x42, 0xf5,
	0xd5, 0xb3, 0x6c, 0x85, 0x03, 0xdf, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xac, 0x56, 0xfa,
	0x04, 0x02, 0x00, 0x00,
}
