apiVersion: v1
kind: Service
metadata:
  name: extraction-svc
  labels:
    app: extraction
    tier: frontend
spec:
  selector:
    app: extraction
    tier: frontend
  ports:
  - name: extraction
    port: 8000
    protocol: TCP
    targetPort: castor-grpc
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: extraction
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: extraction
        tier: frontend
        release: stable
    spec:
      restartPolicy: Always
      containers:
      - name: castor
        image: gcr.io/finciero-gold/castor:v0.0.1
        ports:
        - name: castor-grpc
          containerPort: 4000
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
        args:
        - -castor-cert
        - $(CASTOR_CERT)
        - -castor-key
        - $(CASTOR_KEY)
        - -kanon-cert
        - $(KANON_CERT)
        - -saga-cert
        - $(SAGA_CERT)
        env:
        - name: CASTOR_CERT
          value: "/etc/castor/castorcert"
        - name: CASTOR_KEY
          value: "/etc/castor/castorkey"
        - name: KANON_CERT
          value: "/etc/kanon/kanoncert"
        - name: SAGA_CERT
          value: "/etc/saga/sagacert"
        volumeMounts:
          - mountPath: /etc/castor
            name: castor
            readOnly: true
          - mountPath: /etc/kanon
            name: kanon
            readOnly: true
          - mountPath: /etc/saga
            name: saga
            readOnly: true
        command: ["castor"]
      - name: kanon
        image: gcr.io/finciero-gold/kanon:v0.0.1
        imagePullPolicy: Never
        ports:
        - name: kanon-grpc
          containerPort: 4001
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
        args:
        - -kanon-cert
        - $(KANON_CERT)
        - -kanon-key
        - $(KANON_KEY)
        env:
        - name: KANON_CERT
          value: "/etc/kanon/kanoncert"
        - name: KANON_KEY
          value: "/etc/kanon/kanonkey"
        volumeMounts:
          - mountPath: /etc/kanon
            name: kanon
            readOnly: true
        command: ["kanon"]
      - name: saga
        image: gcr.io/finciero-gold/saga:v0.0.1
        imagePullPolicy: Never
        ports:
        - name: saga-grpc
          containerPort: 4002
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
        args:
        - -saga-cert
        - $(SAGA_CERT)
        - -saga-key
        - $(SAGA_KEY)
        env:
        - name: SAGA_CERT
          value: "/etc/saga/sagacert"
        - name: SAGA_KEY
          value: "/etc/saga/sagakey"
        volumeMounts:
          - mountPath: /etc/saga
            name: saga
            readOnly: true
        command: ["saga"]
      volumes:
        - name: castor
          secret:
            secretName: castorsecret
        - name: kanon
          secret:
            secretName: kanonsecret
        - name: saga
          secret:
            secretName: sagasecret