apiVersion: v1
kind: Service
metadata:
  name: sanctuary
  labels:
    app: sanctuary
    tier: frontend
spec:
  selector:
    app: sanctuary
    tier: frontend
  ports:
  - name: frontend
    port: 8080
    protocol: TCP
    targetPort: http
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sanctuary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sanctuary
        tier: frontend
        release: stable
    spec:
      containers:
      - name: sanctuary
        image: gcr.io/finciero-gold/sanctuary:v0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 2000
          name: http
        command: ["sanctuary"]
