apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aries
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aries
        tier: backend
        release: stable
    spec:
      containers:
      - name: mu
        image: gcr.io/finciero-gold/mu:v0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 2000
          name: mu-grpc
        command: ["gemini"]
